version: '3.8'

services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: autocar
    ports:
      - "5432:5432"  # Exposed to host machine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d autocar"]

  backend:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_NAME: autocar
    ports:
      - "3000:3000"  # Exposed to host machine
    depends_on:
      db:
        condition: service_healthy